version: "3.8"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: shiva
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fpl_suggested_transfers
    volumes:
      - "./sql_initialisation/init.sql:/docker-entrypoint-initdb.d/init.sql"

  fpl-app:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
